// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "description": "API que calcula a taxa de conversão por minuto com filtros",
    "title": "API de Conversão Ilumeo",
    "contact": {},
    "version": "1.0"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "schemes": [],
  "paths": {
    "/api/conversao": {
      "get": {
        "tags": [
          "Conversão"
        ],
        "summary": "Retorna evolução da taxa de conversão",
        "description": "Agrupamento por minuto com possibilidade de filtro por canal e intervalo de data",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "canal",
            "in": "query",
            "description": "Canal de origem (ex: email, MOBILE)",
            "required": false,
            "type": "string"
          },
          {
            "name": "inicio",
            "in": "query",
            "description": "Data de início (formato ISO)",
            "required": false,
            "type": "string",
            "format": "date-time"
          },
          {
            "name": "fim",
            "in": "query",
            "description": "Data de fim (formato ISO)",
            "required": false,
            "type": "string",
            "format": "date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Lista com dados agregados por minuto",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "intervalo": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "total_registros": {
                    "type": "integer"
                  },
                  "conversoes": {
                    "type": "integer"
                  },
                  "taxa_conversao": {
                    "type": "number",
                    "format": "float"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno no servidor"
          }
        }
      }
    }
  }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Conversão Ilumeo",
	Description:      "API que calcula a taxa de conversão por minuto com filtros",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
